### PR TITLE
Swift 4.2

### LINKED ISSUE #110: Tests fail in iOS 11.3.1 on iPhone 8+
In iOS 11.3.1 the tests for the `Concat` and `LocalResponseNorm` layers fail in iPhone 8 and iPhone X.
They work in iOS 11.3 (to my understanding) and also if run on iPhone 7 or below.

I am not sure this is a Bender or an iOS issue.

### PR DESCRIPTION
**Pull request by mats-claassen**
Compiles in Xcode 10. Tests are working again as well

Fixes #110

### CODE REVIEW

File: Sources/Core/ParameterDataSource.swift [hunk 1]
```diff
@@ -10,6 +10,14 @@ import MetalPerformanceShaders
 @available(iOS 11.0, *)
 public class ConvolutionDataSource: NSObject, MPSCNNConvolutionDataSource {
 
+    public func copy(with zone: NSZone? = nil) -> Any {
```
Comment (bryant1410) [inline Sources/Core/ParameterDataSource.swift]: Is this change also related to the new Xcode?

Comment (mats-claassen) [reply Sources/Core/ParameterDataSource.swift]: To iOS 12 I guess, but yes
